### ISSUE TITLE
Products recommendation based on behaviour statistics

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-module-product-recommendations#1]
@IgorisB commented on [Tue Mar 14 2017](https://github.com/VirtoCommerce/vc-platform/issues/757)

**Purpose**
Provide product recommendations for the customer based on behaviour statistics

**Requirements**
- [ ] should not decrease page loading time
- [ ] use cognitive methods: https://azure.microsoft.com/en-us/services/cognitive-services/recommendations/
- [ ] send usage events automatically (One of the following: - Click on product, - RecommendationClick, - AddShopCart, - RemoveShopCart, - Purchase) to improve recommendations 
- [ ] click on recommended item should be sent to Google analytic
- [ ] catalog updates should be automatically uploaded to recommendation service
- [ ] use user to item type of recommendations

**Related issues**
- [ ] ?

**User stories**
Use following user role in the use cases:
- [ ] Customer
- [ ] Manager
- [ ] Developer
- [ ] IT Administrator - infrastructure, azure admin
- [ ] VC Administrator - VC admin site 

Use cases:
- [ ] As a Customer, I want to see automatically recommended items on product page 
- [ ] As a VC Administrator, I want to install and configure module in Admin site 
- [ ] As a VC Administrator, I want to upload all catalog items into Recommendations API.
- [ ] As a VC Administrator, I want to upload initial usage file so that recommendation service will be trained
- [ ] As a Manager, I want to view some statistics.
- [ ] As a Developer, I want to have some snippets and script to install on storefront.

**Acceptance criteria**
- [ ] Must see recommendations list in the http://demo.virtocommerce.com 
- [ ] Must be module installed to http://demo.virtocommerce.com/admin
- [ ] Must be module documentation: configurations, storefront developer guide
- [ ] Module must be optional (module uninstall should not crash storefront)

**Definition of Done**
- [ ] E2E tests for http://demo.virtocommerce.com
- [ ] Page load must not be greater than 1 sec

---

@miguelhasse commented on [Thu Mar 16 2017](https://github.com/VirtoCommerce/vc-platform/issues/757#issuecomment-286912533)

How about integration with Microsoft Cognitive Services Recommendations?
https://www.microsoft.com/cognitive-services/en-us/recommendations-api

---

@Woland2k commented on [Thu Mar 16 2017](https://github.com/VirtoCommerce/vc-platform/issues/757#issuecomment-286912806)

@miguelhasse this is what we planning to use for this task, you can see related tasks already mention it here: https://github.com/VirtoCommerce/vc-platform/projects/1

---

@miguelhasse commented on [Thu Mar 16 2017](https://github.com/VirtoCommerce/vc-platform/issues/757#issuecomment-286920693)

@Woland2k I also have this integration on my backlog :) let me know if I can help.

---

@Woland2k commented on [Thu Mar 16 2017](https://github.com/VirtoCommerce/vc-platform/issues/757#issuecomment-286921398)

@miguelhasse first we need to define user use cases I believe it needs to:

1. Show recommended products on homepage.
2. Show recommendations on product and cart pages.

And more advanced, results in category pages should display receommended products first.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
