### ISSUE TITLE
How can we add recommendations in virto commerce

### ISSUE THREAD

**Issue by Shagun-Bansal** [VirtoCommerce/vc-module-product-recommendations#5]
How can we add recommendations in virto commerce . Do we need to use recommendation module or there is some other way to do this as in the recommendation module it is mentioned that this module is deprecated so anyone pls can clear this point .

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7592 has been created

**Comment by Shagun-Bansal** [comment]
@mvktsk I don't have access to Jira on virtocommerce.atlassian.net.

**Comment by OlegoO** [comment]
@Shagun-Bansal The module was based on Azure API which was marked deprecated. For recommendations, we recommend using either Associations - Dynamic or Static or integration with 3rd party services. 

https://www.youtube.com/watch?v=h-YZuKBO7b8

**Comment by Shagun-Bansal** [comment]
@OlegoO How can we show recommendations based on user searching data and how can we do do 3rd party integration these things are not explained in the video that you have shared. So can you please tell me how can we do these things that I mentioned above.
